version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm

          # In production you should use endpoint https://api.knapsackpro.com
          # which is default so it means you don't need to set KNAPSACK_PRO_ENDPOINT
          # Below endpoint is just for internal tests by KnapsackPro developers.
          KNAPSACK_PRO_ENDPOINT: https://api-staging.knapsackpro.com

    working_directory: ~/app
    steps:
      # dependencies
      # @knapsack-pro/core project
      - run: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git)

      - restore_cache:
          keys:
          - v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-knapsack-pro-core-

      - run: cd ~/knapsack-pro-core-js && npm install
      - run: cd ~/knapsack-pro-core-js && npm run tsc
      - run: cd ~/knapsack-pro-core-js && npm link

      - save_cache:
          paths:
            - ~/knapsack-pro-core-js/node_modules
          key: v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}

      # @knapsack-pro/cypress project
      - run: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-cypress.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-cypress.git)

      - restore_cache:
          keys:
          - v1-knapsack-pro-cypress-{{ checksum "~/knapsack-pro-cypress/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-knapsack-pro-cypress-

      - run: cd ~/knapsack-pro-cypress && npm install
      - run: cd ~/knapsack-pro-cypress && npm link @knapsack-pro/core
      - run: cd ~/knapsack-pro-cypress && npm run tsc
      - run: cd ~/knapsack-pro-cypress && npm link

      - save_cache:
          paths:
            - ~/knapsack-pro-cypress/node_modules
          key: v1-knapsack-pro-cypress-{{ checksum "~/knapsack-pro-cypress/package.json" }}

      # cypress-example-kitchensink project
      - checkout
      - restore_cache:
          key: v2-app-{{ .Branch }}-{{ checksum "package.json" }}
          key: v2-app-{{ .Branch }}
          key: v2-app-
      - run:
          name: Install Dependencies
          command: npm ci
      - run: npm link @knapsack-pro/cypress
      - save_cache:
          key: v2-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
            - .git
      - run: npm run types
      # it requires Record Key for Cypress
      #- run: npm run test:ci:record

      # don't run the whole test suite for now
      # - run: npm run test

      # run tests with @knapsack-pro/cypress
      - run:
          name: Run http server with the app
          command: npm run start:ci
          background: true

      - run: npm run test:tiny_test_suite

      # - run: npx knapsack-pro-cypress
