version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      # dependencies
      # @knapsack-pro/core project
      - restore_cache:
          keys:
          - v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-knapsack-pro-core-

      - run: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git)
      - run: cd ~/knapsack-pro-core-js && npm install
      - run: cd ~/knapsack-pro-core-js && npm run tsc

      - save_cache:
          paths:
            - ~/knapsack-pro-core-js/node_modules
          key: v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}

      # @knapsack-pro/cypress project
      - restore_cache:
          keys:
          - v1-knapsack-pro-cypress-{{ checksum "~/knapsack-pro-cypress/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-knapsack-pro-cypress-

      - run: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-cypress.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-cypress.git)
      - run: cd ~/knapsack-pro-cypress && npm install
      - run: cd ~/knapsack-pro-cypress && npm run tsc

      - save_cache:
          paths:
            - ~/knapsack-pro-cypress/node_modules
          key: v1-knapsack-pro-cypress-{{ checksum "~/knapsack-pro-cypress/package.json" }}

      # cypress-example-kitchensink project
      - checkout
      - restore_cache:
          key: v2-app-{{ .Branch }}-{{ checksum "package.json" }}
          key: v2-app-{{ .Branch }}
          key: v2-app-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v2-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
            - .git
      - run: npm run types
      # it requires Record Key for Cypress
      #- run: npm run test:ci:record

      - run: npm run test
      - run: npm run test:tiny_test_suite
